/**
 * User-facing Chinese copy — the single source of truth for UI strings.
 *
 * Every visible label, tooltip and aria-label lives here, grouped by UI
 * domain (layout / chat / settings / …), so wording stays consistent and
 * a future localization pass has one file to swap. Technical identifiers,
 * test ids, log messages and session-title *data* defaults stay out —
 * those belong to the stores, not the copy layer.
 *
 * Conventions:
 *  - Static copy: plain string properties.
 *  - Interpolated copy: small arrow functions (keeps call sites honest
 *    about their parameters).
 *  - Punctuation is full-width Chinese（，。…）except inside technical
 *    terms like "Ctrl+K" or "Worktree".
 */
export const strings = {
  /** Cross-domain shared words. */
  common: {
    close: "关闭",
    retry: "重试",
    settings: "设置",
    delete: "删除",
  },

  /** App-shell domain: TopBar, Sidebar, banners, overlays, footer. */
  layout: {
    topbar: {
      toggleSidebar: "切换侧栏",
      openCommandPalette: "打开命令面板",
      commandPaletteHint: "命令面板（Ctrl+K）",
      preview: "预览",
      settings: "设置",
    },

    sidebar: {
      brandTagline: "AI 编码助手",
      projectOptions: "项目选项",
      sessionOptions: "任务选项",
      untitled: "（未命名）",
      createWorktreeTask: "创建隔离的 Worktree 任务",
      newProject: "新建项目",
      searchTaskHistory: "搜索任务历史",
      searchHistoryPlaceholder: "搜索历史…",
      clearHistorySearch: "清除搜索",
    },

    commandPalette: {
      title: "命令面板",
      newTaskSubtitle: "新建聊天会话",
      previewSubtitle: "切换实时预览面板",
      skillsSubtitle: "技能库",
    },

    connection: {
      connectingTitle: "正在连接 Agent",
      connectingDetail: "正在准备本地运行时。",
      disconnectedTitle: "与 Agent 的连接已断开",
      disconnectedDetail: "后台正在自动重试。",
      errorTitle: "连接出错",
      errorDetail: "本地 Agent 未响应。",
      retry: "重试",
      dismiss: "关闭连接提示",
      nextRetry: (seconds: number) => `${seconds} 秒后重试。`,
    },

    storage: {
      title: "本地存储不可用",
      detail: "新的会话与消息不会被保存。重启 Agent 后通常可恢复。",
    },

    errorBoundary: {
      title: "出错了",
      reload: "重新加载组件",
    },

    gitStatus: {
      loading: "加载中…",
      clean: "无变更",
      changesCount: (count: number) => `${count} 处变更`,
      branchTitle: (branch: string, label: string) => `分支 ${branch} — ${label}`,
      loadingTitle: "正在加载 Git 状态…",
      panelLabel: (branch: string) => `${branch} 分支的 Git 状态`,
      modified: "已修改",
      staged: "已暂存",
      untracked: "未跟踪",
      workingTreeClean: "工作区无变更。",
      viewDiff: "查看差异",
      viewLog: "查看日志",
    },

    workspace: {
      switchedToast: "已切换工作区",
      empty: "暂无工作区",
    },

    theme: {
      toLight: "切换到浅色模式",
      toDark: "切换到深色模式",
      light: "浅色模式",
      dark: "深色模式",
    },

    notifications: {
      title: "通知",
      bellLabel: (unread: number) =>
        unread > 0 ? `通知（${unread} 条未读）` : "通知",
      unreadSuffix: (unread: number) => `（${unread} 条未读）`,
      markAllReadTitle: "全部标为已读",
      readAll: "全部已读",
      close: "关闭通知",
      markRead: "标为已读",
      delete: "删除",
    },

    shortcuts: {
      title: "键盘快捷键",
      close: "关闭快捷键面板",
      items: [
        { key: "?", label: "打开快捷键面板" },
        { key: "Esc", label: "关闭面板" },
        { key: "Enter", label: "发送消息" },
        { key: "Shift Enter", label: "换行" },
        { key: "@", label: "选择子 Agent" },
        { key: "Tab", label: "确认选中项" },
      ],
    },

    userBadge: {
      defaultName: "用户",
      defaultEmail: "未绑定邮箱",
      defaultPlan: "个人版",
      editPlan: "点击编辑计划名称",
      settings: "设置",
      signOut: "退出登录",
    },

    toast: {
      dismiss: "关闭",
    },
  },

  /** Chat domain: header, composer, messages, banners, mention picker. */
  chat: {
    header: {
      titleInput: "会话标题",
      renameHint: "双击重命名",
      rename: "重命名会话",
      newTask: "新建任务",
      newButton: "+ 新建",
      search: "搜索消息",
      searchPlaceholder: "搜索消息…",
      filtering: "筛选中",
      refresh: "刷新",
      refreshSessions: "刷新会话列表",
      more: "更多",
      moreOptions: "更多选项",
      clearSearch: "清除搜索",
    },

    headerStatus: {
      sending: "发送中",
      streaming: "生成中",
      error: "错误",
      ready: "就绪",
    },

    messageStatus: {
      queued: "排队中",
      sending: "发送中",
      streaming: "生成中",
      failed: "失败",
      cancelling: "停止中…",
      cancelled: "已停止",
    },

    input: {
      dropFilesHere: "松开以添加文件…",
      attachFile: "添加文件",
      attachTextFile: "添加文本文件",
      attachImage: "添加图片",
      attachAnImage: "添加一张图片",
      messageLabel: "消息输入",
      placeholder: "问 MiniMax 任何问题…（Enter · @agent · @repo · #file）",
      stopping: "正在停止…",
      stop: "停止",
      stopVoice: "停止语音输入",
      startVoice: "开始语音输入",
      listening: "正在聆听…点击停止",
      voiceInput: "语音输入",
      loadingContext: "正在加载上下文…",
      send: "发送",
    },

    actions: {
      copy: "复制",
      copied: "已复制",
      copyMessage: "复制消息",
      messageCopied: "消息已复制",
      copyFailed: "复制失败",
      copyFailedDetail: "剪贴板访问被拒绝。",
      retry: "重试",
      menu: "消息操作",
    },

    list: {
      jumpToLatest: "跳到最新消息",
      newCount: (count: number) => `${count} 条新消息`,
      latest: "最新",
      searchSummary: (shown: number, total: number) => `共 ${total} 条消息，匹配 ${shown} 条`,
      loadEarlier: (shown: number, hidden: number) =>
        `↑ 加载更早的 ${shown} 条消息（还有 ${hidden} 条）`,
    },

    fileRefs: {
      groupLabel: "引用的文件",
      copyReference: "复制文件引用",
    },

    attachments: {
      removeFile: (name: string) => `移除 ${name}`,
    },

    toolCall: {
      fallbackName: "工具",
      mcpServer: (server: string) => `MCP 服务器：${server}`,
    },

    mermaid: {
      copySource: "复制图表源码",
      renderFailed: "无法渲染 Mermaid 图表",
      rendering: "正在渲染图表…",
    },

    context: {
      title: (used: string, total: string) => `上下文：已用 ${used} / 上限 ${total} tokens`,
    },

    turnSummary: "本轮摘要",
    sources: "来源",

    memory: {
      savedCount: (count: number) => `已保存 ${count} 条记忆`,
    },

    providerBanner: {
      noModelTitle: "未选择模型",
      providerDisabledTitle: "提供商已禁用",
      demoTitle: "演示模式",
      noModelDetail: "开始任务前请先选择模型。",
      providerDetail: (model: string, provider: string) =>
        `${model} 将返回模拟响应，直到 ${provider} 配置 API 密钥。`,
      unavailableDetail: (model: string) => `${model} 关联的提供商不可用。`,
      chooseModel: "选择模型",
      configureProvider: "配置提供商",
    },

    mention: {
      agentHeader: "生成子 Agent",
      repoHeader: "仓库上下文",
      fileHeader: "文件上下文",
      loadFailed: "加载 Agent 失败",
    },

    modelSelector: {
      fallback: "模型",
    },

    composer: {
      exportSession: "将当前会话导出为 Markdown",
    },

    toast: {
      sessionCreateFailed: "创建会话失败",
      fileReadFailed: "读取文件失败",
      imageReadFailed: "读取图片失败",
      subagentFailed: "子 Agent 生成失败",
      mentionTitle: "上下文提及",
      mentionNeedQuestion: "请在 @repo 后补充问题。",
      mentionLoadFailed: "加载提及上下文失败",
    },
  },

  /** Settings domain: page shell, tabs, and per-tab copy (R29). */
  settings: {
    page: {
      title: "设置",
      hint: "管理模型、Provider、权限、定时任务与 API 密钥。",
      close: "关闭设置",
      sections: "设置分区",
      groupCore: "核心",
      groupAutomation: "自动化",
      groupAgents: "Agent",
      groupGovernance: "治理",
      tabModels: "模型",
      tabProviders: "Provider",
      tabApiKey: "API 密钥",
      tabPermissions: "权限",
      tabMcp: "MCP 服务器",
      tabMemory: "记忆",
      tabPlugins: "插件",
      tabData: "数据",
      tabScheduled: "定时任务",
      tabWorkflows: "工作流",
      tabWebhooks: "Webhook",
      tabAgents: "子 Agent",
      tabTeams: "团队",
      tabAudit: "审计",
    },

    models: {
      title: "可用模型",
      hint: "先选择当前使用的模型，再在下方管理各 Provider 的模型注册表。",
      refresh: "刷新",
      registryTitle: "Provider 模型注册表",
      loadingProviders: "正在加载 Provider…",
    },

    modelsRow: {
      current: "当前",
      contextK: (k: string) => `${k}k 上下文`,
      supportsTools: "支持工具",
      selected: "已选择",
      use: "使用",
    },

    modelsRegistry: {
      modelsCount: (count: number) => `${count} 个模型`,
      removeModelAria: (id: string) => `移除 ${id}`,
      modelIdAria: (provider: string) => `${provider} 模型 ID`,
      modelNameAria: (provider: string) => `${provider} 模型显示名`,
      modelCtxAria: (provider: string) => `${provider} 上下文窗口`,
      placeholderId: "模型 ID…",
      placeholderName: "显示名…",
      placeholderCtx: "上下文…",
      add: "添加",
      removeConfirmTitle: (id: string) => `移除模型 ${id}？`,
      removeConfirmDesc: (provider: string) =>
        `该模型将从 ${provider} 移除。已选中它的会话需要另选一个可用模型。`,
      removeConfirmLabel: "移除模型",
    },

    apiKey: {
      statusKeyring: "已存入系统钥匙串",
      statusEnv: "正在使用环境变量",
      statusNone: "未配置——Agent 处于模拟模式",
      title: "MiniMax API 密钥",
      hintLead:
        "旧版内置 MiniMax Provider 使用的密钥。多 Provider 配置请使用「Provider」标签页。" +
        "存入系统钥匙串（Windows 凭据管理器 / macOS 钥匙串 / Linux Secret Service）；" +
        "若钥匙串无条目，则回退到",
      hintTail: "环境变量。",
      inputLabel: "MiniMax API 密钥",
      reveal: "显示 API 密钥",
      hide: "隐藏 API 密钥",
      panelNew: "粘贴密钥以存入系统钥匙串",
      panelReplace: "替换钥匙串条目",
      save: "保存",
      writeNote: "保存时密钥写入系统钥匙串，写入后不再经由网络回传。",
      keyringEntry: "钥匙串条目",
      clearButton: "清除钥匙串",
      clearConfirmTitle: "清除旧版 MiniMax API 密钥？",
      clearConfirmDesc:
        "使用旧版密钥的 MiniMax 请求将停止，直至保存新密钥。已有会话不会被删除。",
      clearConfirmLabel: "清除 API 密钥",
      clearNoteLead: "从系统钥匙串删除该条目。不影响",
      clearNoteTail: "环境变量。",
    },

    data: {
      title: "数据可移植",
      hint: "在本地 Agent 数据库与外部之间搬入搬出数据。导出生成可移植的 JSON 包；备份生成本机保存的文件级 SQLite 快照。",
      exportTitle: "导出为 JSON",
      exportDesc:
        "把全部业务表（会话、消息、记忆、权限……）导出为一个自描述 JSON 文档。" +
        "带 schema 版本，旧版本会拒绝导入新版本的文件，而不是损坏自身。",
      exportButton: "导出数据",
      importTitle: "从 JSON 导入",
      importDesc:
        "恢复一个导出文件。替换语义：文件中的每张表在单个事务内完整覆盖当前内容——" +
        "要么全部落地，要么全部不做。未知表与漂移的列会被跳过，绝不致命。",
      importButton: "选择文件…",
      importConfirmTitle: "导入此导出文件？",
      importConfirmDesc: (rows: number, schema: number) =>
        `替换式导入：文件中出现的每张表都会覆盖当前数据（${rows} 行，schema v${schema}）。` +
        `此操作不可撤销——如无把握请先备份。`,
      importConfirmLabel: "导入",
      backupTitle: "备份快照",
      backupDescLead:
        "通过 online backup API 热复制 SQLite 数据库——含 schema、WAL 内容与派生索引（全文、向量）——写入",
      backupDescTail: "，文件名带 UTC 时间戳。Agent 保持运行；源库只读。",
      backupButton: "立即备份",
      diagTitle: "诊断包",
      diagDesc:
        "导出一份脱敏诊断 JSON（版本 / 平台 / 配置枚举 / 各表行数 / 最近日志尾），" +
        "可直接附在问题报告里。配置只含枚举与计数，绝不含密钥；路径仅保留目录名。",
      diagButton: "导出诊断包",
      footerNote:
        "导出是跨版本格式（例如机器间迁移）；备份是同版本的灾备格式。大规模导入前请至少保留一份备份。",
      exportOk: (rows: number, tables: number, file: string) =>
        `已导出 ${tables} 张表共 ${rows} 行 → ${file}`,
      exportFail: (err: string) => `导出失败：${err}`,
      importOk: (rows: number, tables: number, skipped: string) =>
        `已导入 ${tables} 张表共 ${rows} 行${skipped}。`,
      importSkipped: (n: number) => `（跳过 ${n} 个未知表）`,
      importFail: (err: string) => `导入失败：${err}`,
      backupOk: (path: string, size: string) => `备份已写入：${path}（${size}）`,
      backupFail: (err: string) => `备份失败：${err}`,
      diagOk: (version: string, tables: number, file: string) =>
        `已导出诊断包（v${version}，${tables} 张表）→ ${file}`,
      diagFail: (err: string) => `诊断包导出失败：${err}`,
    },

    audit: {
      title: "审计日志",
      hint: "每次工具调度都有记录，全程可追溯。用它审查 Agent 何时做了什么。",
      refresh: "刷新",
      statTotal: "总调用",
      statTools: "使用工具数",
      statSuccess: "成功数",
      filterLabel: "按工具筛选：",
      filterAll: "全部",
      colTime: "时间",
      colTool: "工具",
      colStatus: "状态",
      colDuration: "耗时",
      colPermission: "权限",
      colError: "错误",
      prev: "← 上一页",
      next: "下一页 →",
      page: (page: number, total: number) => `第 ${page} / ${total} 页`,
    },

    permissions: {
      title: "权限规则",
      hintLead: "模式与工具调用参数匹配。决策为",
      hintMid1: "的规则跳过确认弹窗；",
      hintMid2: "拦截调用；",
      hintTail: "总是询问。",
      addTitle: "添加规则",
      fieldTool: "工具",
      placeholderTool: "如 bash…",
      fieldPattern: "参数模式",
      placeholderPattern: "如 ^git status$…",
      fieldDecision: "决策",
      add: "添加",
      empty: "暂无权限规则",
      savedToast: "规则已保存",
      deleteTitle: "删除这条权限规则？",
      deleteDesc: (tool: string, pattern: string) =>
        `工具 ${tool}（${pattern}）的这条规则将不再约束后续工具调用。`,
      deleteLabel: "删除规则",
      defaultBadge: " · 默认",
      defaultTitle: "出厂默认——可用选择器覆盖；不可删除",
      decisionAria: (tool: string, pattern: string) => `${tool} ${pattern} 的决策`,
      deleteAria: "删除规则",
    },

    memory: {
      title: "长期记忆",
      hintLead: "Agent 为匹配的项目或会话召回的事实、偏好、决定与经验。通过",
      hintTail: "系统提示块注入。",
      addTitle: "添加记忆",
      placeholder: "如：偏好 TypeScript strict 模式；新增 IPC handler 必须补测试…",
      category: "分类",
      confidence: (pct: string) => `置信度 ${pct}%`,
      add: "添加",
      contentRequiredTitle: "请输入内容",
      contentRequiredDesc: "添加前请先输入记忆内容。",
      addedToast: "记忆已添加",
      deleteTitle: "删除这条记忆？",
      deleteLabel: "删除",
      searchPlaceholder: "搜索记忆…",
      clearSearch: "清除搜索",
      filterProject: "按项目 ID 筛选",
      filterSession: "按会话 ID 筛选",
      count: (total: number) => `${total} 条记忆`,
      emptySearch: "没有匹配的记忆",
      empty: "暂无记忆",
      rowProject: (id: string) => `项目：${id}`,
      rowSession: (id: string) => `会话：${id}`,
      rowUpdated: (rel: string) => `更新于 ${rel}`,
      deleteAria: "删除记忆",
    },

    plugins: {
      title: "插件",
      hint: (enabled: number, failed: number) =>
        `${enabled} 个已启用${failed > 0 ? `，${failed} 个失败` : ""}。` +
        `运行时开关仅存于内存，清单持久化落地后才会长期保存。`,
      reload: "重新加载",
      loadFailed: "加载插件失败",
      toggleFailed: "切换插件状态失败",
      reloadedToast: "插件已重载",
      reloadedDetail: (loaded: number, failed: number) =>
        `${loaded} 个加载成功，${failed} 个失败`,
      reloadFailed: "重载插件失败",
      loading: "正在加载插件…",
      emptyHint: "插件在运行时从已配置的插件根目录中发现。",
      statusFailed: "加载失败",
      statusEnabled: "已启用",
      statusDisabled: "已停用",
      hooks: "钩子",
      mcp: "MCP",
      permissions: "权限",
      on: "开",
      off: "关",
    },

    providers: {
      title: "LLM Provider",
      hint: "管理 LLM Provider 与 API 密钥。已启用 Provider 的模型会出现在模型选择器中。",
      add: "添加 Provider",
      loading: "正在加载 Provider…",
      builtinDeleteTitle: "无法删除",
      builtinDeleteDesc: "内置 MiniMax Provider 不可移除。",
      deleteTitle: (name: string) => `删除 ${name}？`,
      deleteDesc:
        "这会从 MiniMax Code 移除该 Provider、其模型注册表与其保存的 API 密钥。此操作不可撤销。",
      deleteLabel: "删除 Provider",
      deletedToast: "Provider 已删除",
      keySavedToast: "API 密钥已保存",
      clearKeyTitle: (name: string) => `清除 ${name} 的 API 密钥？`,
      clearKeyDesc:
        "通过该 Provider 发起的真实模型请求将停止，直至保存新密钥。已有会话不会被删除。",
      clearKeyLabel: "清除 API 密钥",
      keyClearedToast: "API 密钥已清除",
      form: {
        editTitle: "编辑 Provider",
        newTitle: "新建 Provider",
        cancel: "取消",
        presetsLabel: "快速预设：",
        fieldName: "名称",
        placeholderName: "如 DeepSeek…",
        fieldProtocol: "协议",
        fieldBaseUrl: "Base URL",
        apiKeyLabel: "API 密钥",
        keepNote: "留空保持当前值",
        placeholderKeyKeep: "留空保持当前值…",
        showKey: "显示 API 密钥",
        hideKey: "隐藏 API 密钥",
        modelsLabel: "模型",
        removeModelAria: (id: string) => `移除 ${id}`,
        modelIdAria: "模型 ID",
        placeholderModelId: "模型 ID…",
        modelNameAria: "模型显示名",
        placeholderModelName: "显示名…",
        modelCtxAria: "上下文窗口",
        placeholderModelCtx: "上下文…",
        addModel: "添加模型",
        update: "更新",
        create: "创建",
        updatedToast: "Provider 已更新",
        createdToast: "Provider 已创建",
      },
      card: {
        disabled: "已停用",
        keyOk: "密钥 ✓",
        noKey: "未配置密钥",
        expandAria: (name: string) => `展开 ${name}`,
        collapseAria: (name: string) => `折叠 ${name}`,
        editAria: "编辑 Provider",
        deleteAria: "删除 Provider",
        modelsTitle: (count: number) => `模型（${count}）`,
        apiKeyTitle: "API 密钥",
        keyAria: (name: string) => `${name} 的 API 密钥`,
        placeholderEnter: "输入 API 密钥…",
        placeholderReplace: "替换密钥…",
        showKeyAria: (name: string) => `显示 ${name} 的 API 密钥`,
        hideKeyAria: (name: string) => `隐藏 ${name} 的 API 密钥`,
        save: "保存",
        clear: "清除",
      },
    },

    scheduled: {
      title: "定时任务",
      hintLead: "Agent 按计划运行的 Cron 任务。使用 5 段 cron 表达式（如",
      hintTail: "表示每 5 分钟一次）。",
      newTitle: "新建任务",
      fieldName: "任务名称",
      placeholderName: "如：每夜审查…",
      fieldCron: "Cron 表达式",
      placeholderCron: "如 0 2 * * *…",
      fieldPrompt: "提示词",
      placeholderPrompt: "如：审查最近的改动…",
      create: "创建",
      createdToast: "任务已创建",
      empty: "暂无定时任务",
      deleteTitle: (name: string) => `删除定时任务 ${name}？`,
      deleteDesc: "该任务将停止运行，其计划将被永久移除。",
      deleteLabel: "删除任务",
      collapse: "折叠",
      expand: "展开",
      noPrompt: "（无提示词）",
      enabled: "已启用",
      disabled: "已停用",
      runNowAria: "立即运行",
      deleteAria: "删除任务",
      noRuns: "尚无任务运行记录。",
      running: "运行中",
    },

    workflows: {
      title: "工作流",
      hint: "由 Webhook、定时任务或 Agent 事件触发的自动化工作流。配置触发条件与动作步骤。",
      refresh: "刷新",
      new: "新建",
      createTitle: "新建工作流",
      fieldName: "名称",
      placeholderName: "如：Pull request review…",
      fieldTrigger: "触发器",
      triggerWebhook: "Webhook",
      triggerSchedule: "定时任务",
      triggerAgentEvent: "Agent 事件",
      fieldDescription: "描述",
      placeholderDesc: "如：审查传入的 pull request…",
      cancel: "取消",
      create: "创建",
      stepsBadge: (n: number) => `${n} 个步骤`,
      enabled: "已启用",
      disabled: "已停用",
      runAria: (name: string) => `运行工作流 ${name}`,
      runTitle: "手动触发此工作流",
      deleteAria: (name: string) => `删除工作流 ${name}`,
      deleteTitle: (name: string) => `删除工作流 ${name}？`,
      deleteDesc: "工作流定义及其触发配置将被永久移除。",
      deleteLabel: "删除工作流",
      runs: (n: number) => `运行：${n}`,
      last: (rel: string) => `上次：${rel}`,
      footer: (total: number) => `已配置 ${total} 个工作流`,
    },

    agents: {
      title: "子 Agent",
      hintLead: "在聊天中通过",
      hintTail: "召唤子 Agent 完成专项任务；这里管理它们的定义。",
      new: "新建 Agent",
      panelTitle: "新建 Agent",
      fieldName: "Agent 名称",
      placeholderName: "如 code-reviewer…",
      fieldPrompt: "系统提示词",
      placeholderPrompt: "系统提示词…",
      cancel: "取消",
      create: "创建",
      loading: "正在加载 Agent…",
      enabled: "已启用",
      disabled: "已停用",
      deleteAria: (name: string) => `删除 Agent ${name}`,
      deleteTitle: (name: string) => `删除 Agent ${name}？`,
      deleteDesc: "该 Agent 将不再出现在聊天与团队分配中。已有会话历史不会被删除。",
      deleteLabel: "删除 Agent",
    },

    teams: {
      title: "Agent 团队",
      hintLead: "在聊天中通过",
      hintTail: "召唤整支团队协同执行；这里管理团队定义。",
      new: "新建团队",
      formTitle: "新建团队",
      loading: "正在加载团队…",
      fieldName: "名称",
      placeholderName: "如 Review Squad…",
      fieldMembers: "成员",
      cancel: "取消",
      createLabel: "创建团队",
      updateLabel: "更新团队",
      membersCount: (n: number) => `${n} 名成员`,
      editAria: (name: string) => `编辑团队 ${name}`,
      deleteAria: (name: string) => `删除团队 ${name}`,
      deleteTitle: (name: string) => `删除团队 ${name}？`,
      deleteDesc: "团队定义及其 Agent 分配将被永久移除。各个 Agent 会保留。",
      deleteLabel: "删除团队",
      fieldOrchestration: "编排模式",
      modeParallel: "并行",
      modeSequential: "顺序",
      modeRoundRobin: "轮询",
      fieldColor: "颜色",
      useColorAria: (c: string) => `使用团队颜色 ${c}`,
      fieldDescription: "描述",
      placeholderDescription: "如：审查前后端变更…",
      enabled: "已启用",
      disabled: "已停用",
      enable: "启用",
      disable: "停用",
      createdToast: "团队已创建",
    },

    webhooks: {
      title: "Webhook",
      hint: "配置 GitHub / Gitee push 事件与自定义集成的入站 Webhook 端点。",
      refresh: "刷新",
      new: "新建",
      formTitle: "新建 Webhook",
      fieldName: "名称",
      placeholderName: "如 GitHub Push…",
      fieldAgent: "目标 Agent",
      cancel: "取消",
      create: "创建",
      footer: (total: number) => `已配置 ${total} 个 Webhook`,
      secretLabel: "密钥：",
      regenerateAria: "重置密钥",
      regenerateTitle: (name: string) => `重置 ${name} 的密钥？`,
      regenerateDesc:
        "当前 Webhook 密钥将立即失效。请先让发送方更新为新密钥，再继续发送事件。",
      regenerateLabel: "重置密钥",
      deleteAria: (name: string) => `删除 Webhook ${name}`,
      deleteTitle: (name: string) => `删除 Webhook ${name}？`,
      deleteDesc: "发送到该 Webhook 的入站事件将不再触发 MiniMax Code。",
      deleteLabel: "删除 Webhook",
      fieldSource: "来源",
      sourceCustom: "自定义",
      fieldAction: "动作",
      actionSendMessage: "发送消息",
      actionCodeReview: "代码审查",
      enabled: "已启用",
      disabled: "已停用",
      hideSecretAria: "隐藏 Webhook 密钥",
      showSecretAria: "显示 Webhook 密钥",
    },

    mcp: {
      title: "MCP 服务器",
      hint: "连接外部 MCP 工具服务器。桥接的工具会进入 Agent 的工具注册表。",
      addServer: "添加服务器",
      fieldName: "名称",
      placeholderName: "服务器名（如 filesystem）",
      fieldTransport: "传输方式",
      transportStdio: "stdio（本地子进程）",
      transportSse: "SSE（HTTP 流）",
      fieldCommand: "命令",
      commandHint: "以空格分隔的 argv。",
      fieldEnv: "环境变量",
      envHint: "JSON 对象。",
      fieldUrl: "SSE URL",
      fieldToken: "Bearer 令牌",
      tokenHint: "可选 Bearer 令牌",
      fieldHeaders: "请求头",
      headersHint: "JSON 对象。",
      oauthTitle: "OAuth（可选）",
      clientId: "Client ID",
      clientSecret: "Client secret",
      fieldScopes: "Scopes",
      scopesHint: "JSON 列表或逗号分隔。",
      callbackPort: "回调端口",
      portInvalid: "OAuth 回调端口必须是数字。",
      cancel: "取消",
      save: "保存",
      envNotObject: "必须是 JSON 对象。",
      envValuesNotStrings: "所有值必须是字符串。",
      invalidJson: "无效的 JSON。",
      nameRequired: "请填写名称。",
      commandRequired: "stdio 传输必须填写命令。",
      urlRequired: "SSE 传输必须填写 URL。",
      envError: (err: string) => `环境变量：${err}`,
      headersError: (err: string) => `请求头：${err}`,
      invalidInput: "输入无效",
      loadFailed: "加载 MCP 服务器失败",
      addedToast: "MCP 服务器已添加",
      addFailed: "添加 MCP 服务器失败",
      deleteTitle: (name: string) => `删除 ${name}？`,
      deleteDesc: "这将移除已持久化的 MCP 服务器配置。",
      deleteLabel: "删除",
      deletedToast: "MCP 服务器已删除",
      deleteFailed: "删除 MCP 服务器失败",
      updateFailed: "更新 MCP 服务器失败",
      listToolsFailed: (name: string) => `列出 ${name} 的工具失败`,
      toggleToolFailed: "更新工具状态失败",
      loading: "正在加载 MCP 服务器…",
      connected: "已连接",
      disconnected: "未连接",
      tools: "工具",
      enabled: "已启用",
      deleteAria: "删除",
      loadingTools: "正在加载工具…",
      noTools: "没有可用工具。服务器可能未连接。",
      on: "开",
      off: "关",
    },
  },

  panels: {
    fileCount: (n: number) => `${n} 个文件`,

    // PreviewPanel — 实时预览
    preview: {
      placeholderPath: "如：index.html",
      goLabel: "前往",
      reloadAria: "重新加载预览",
      closeAria: "关闭预览",
      loadingAria: "正在加载预览",
      retryLabel: "重试",
      iframeTitle: "实时预览",
      serviceError: (status: number) => `预览服务返回 ${status}`,
      fileNotFound: (path: string) => `预览文件不存在：${path}`,
    },

    // SkillsPanel — 技能面板
    skills: {
      title: "技能",
      subtitle: "启用或停用已安装的技能。内置技能随 Agent 一起发布；可从本地 SKILL.md 导入自定义技能。",
      importTitle: "导入 SKILL.md 文件",
      importing: "正在导入…",
      importLabel: "导入",
      readFailToast: "读取技能文件失败",
      readFailError: "无法读取文件",
      closeAria: "关闭技能面板",
      loading: "正在加载技能…",
      builtinBadge: "内置",
      on: "开",
      off: "关",
      removeAria: (name: string) => `移除技能 ${name}`,
      removeTitle: "移除自定义技能",
    },

    // CodeReviewPanel — 代码审查面板
    codeReview: {
      tabOverview: "总览",
      tabSecurity: "安全",
      tabPerformance: "性能",
      tabStyle: "风格",
      reviewing: "正在审查…",
      reviewDiff: "审查 Diff",
      runAll: "全部运行",
      runAllTitle: "运行全部维度检查",
      clearAria: "清除审查结果",
      emptyHint: "点击「审查 Diff」或「全部运行」开始分析代码。",
      noChanges: "没有变更",
      noChangesDetail: "工作区是干净的——没有可审查的内容。",
      noChangesRaw: "没有可审查的变更。",
      reviewComplete: "审查完成",
      commentCount: (n: number) => `${n} 条意见`,
      reviewFailed: "审查失败",
      allChecksComplete: "全部检查完成",
      findingCount: (n: number) => `共 ${n} 条发现`,
      checkFailed: "检查失败",
      checkFailedRaw: (key: string) => `检查 ${key} 失败。`,
    },

    // ImagePreview — 附件图片缩略图
    imagePreview: {
      alt: (n: number) => `附件图片 ${n}`,
      removeAria: (n: number) => `移除图片 ${n}`,
    },

    // PatchPreviewPanel / PatchFileCard / PatchHunkCard — Patch Studio
    patch: {
      scopeWorking: "工作区",
      scopeStaged: "暂存区",
      scopeBranch: "分支",
      scopeTitle: (label: string) => `${label}差异`,
      refreshAria: "刷新补丁预览",
      snapshotLabel: "快照",
      applyAll: "全部应用",
      revertAll: "全部还原",
      loadFail: "无法加载差异",
      changedFilesAria: "变更文件",
      jumpTitle: (path: string) => `跳转到 ${path}`,
      snapshotClean: "工作区是干净的——无需快照",
      snapshotSaved: "快照已保存",
      partialFail: "补丁操作部分失败",
      partialFailDetail: "部分文件无法处理",
      allApplied: "已应用全部变更",
      allReverted: "已还原全部变更",
      opFail: "补丁操作失败",
      binaryChanged: "二进制文件已变更",
      decisionPending: "待定",
      decisionStaging: "暂存中",
      decisionApproved: "已批准",
      decisionRejecting: "还原中",
      decisionRejected: "已还原",
      decisionFailed: "失败",
      fileApproveTitle: "批准该文件的全部改动块",
      fileApproveOnlyWorking: "仅工作区文件可批准",
      fileUnstageTitle: "取消暂存该文件的全部改动块",
      fileRejectTitle: "还原该文件的全部改动块",
      hunkApproveTitle: "批准并暂存此改动块",
      hunkOnlyWorkingStaged: "仅工作区改动块可暂存",
      hunkUnstageTitle: "拒绝并取消暂存此改动块",
      hunkRejectTitle: "拒绝此改动块",
      hunkResetTitle: "重置改动块决策",
      hunkOpFailed: "操作失败",
      showLess: "收起",
      showFullHunk: "展开完整改动块",
    },
  },
  modals: {
    fileCount: (n: number) => `${n} 个文件`,
    gitViewer: {
      srTitle: "Git 查看器",
      tabDiff: "Diff",
      tabLog: "日志",
      noDiff: "暂无 Diff。",
      noCommits: "未找到提交。",
    },
    confirm: {
      cancel: "取消",
      confirm: "删除",
    },
    patchPreview: {
      showLess: "收起",
      showFullPatch: "展开完整补丁",
    },
    mobile: {
      title: "连接手机",
      generating: "正在生成…",
      generate: "生成配对码",
      tokenLabel: "配对令牌",
      clickToCopy: "点击复制",
      expiresCountdown: (t: string) => `${t} 后过期`,
      expired: "已过期",
      copyToken: "复制令牌",
      copyLink: "复制链接",
      tokenCopied: "令牌已复制",
      linkCopied: "链接已复制",
      copyFailed: "复制失败",
      pairedCount: (n: number) => `已配对设备（${n}）`,
      online: "在线",
      offline: "离线",
      pairedAt: (t: string) => `配对于 ${t}`,
      testPushTitle: "测试推送",
      testPushBody: (name: string) => `来自 MiniMax Code 的问候，${name}！`,
      pushSent: "推送已发送",
      sendTestTitle: "发送测试通知",
      pushTestAria: (name: string) => `向 ${name} 推送测试`,
      unpair: "取消配对",
      unpairAria: (name: string) => `取消配对 ${name}`,
    },
    crash: {
      bannerAria: "上次会话已崩溃",
      bannerTitle: "上次会话异常退出",
      history: "历史",
      dismiss: "忽略",
      historyTitle: "崩溃历史",
      historyEmpty: "暂无崩溃历史",
    },
  },
  rightPanel: {
    tabs: {
      timeline: "时间线",
      diff: "Diff",
      progress: "进度",
      checkpoints: "Checkpoints",
      agents: "Agents",
      subagents: "子 Agent",
      review: "评审",
      teamruns: "团队运行",
      terminal: "终端",
      runner: "Runner",
      codebase: "代码库",
    },
    shell: {
      inspector: "检查器",
      panelsAria: "检查器面板",
      collapse: "折叠右侧面板",
      expand: "展开右侧面板",
      pinned: "已手动固定标签页",
      followRun: "跟随运行",
    },
    timeline: {
      loading: "正在加载运行…",
      unavailable: "运行历史不可用。",
      empty: "暂无活动运行。",
      deny: "拒绝",
      allow: "允许",
      runFallbackTitle: "Agent 运行",
      newEvents: "新事件 ↓",
      showLess: "收起",
      showFull: "展开全部",
      errorPrefix: (msg: string) => `错误：${msg}`,
      codeBlock: "[代码块]",
      stepKinds: {
        thought: "思考",
        status: "状态",
        plan: "计划",
        tool_call: "工具调用",
        observation: "观察",
        approval: "授权",
        patch: "补丁",
        final: "最终回复",
      },
    },
    checkpoint: {
      title: "Checkpoints",
      loadFailed: "加载 Checkpoint 失败",
      noSession: "未选择会话",
      created: "Checkpoint 已创建",
      createFailed: "创建 Checkpoint 失败",
      deleted: "Checkpoint 已删除",
      deleteFailed: "删除 Checkpoint 失败",
      restored: "Checkpoint 已恢复",
      restoreFailed: "恢复 Checkpoint 失败",
      deleteTitle: (label: string) => `删除 Checkpoint ${label}？`,
      deleteDescription: "这将删除已存储的快照元数据，磁盘上的未跟踪副本将成为孤儿文件。",
      deleteConfirm: "删除",
      restoreTitle: (label: string) => `恢复 Checkpoint ${label}？`,
      restoreDescription: "这将把工作区回退到 Checkpoint 状态，未提交的改动可能被覆盖。",
      restoreConfirm: "恢复",
      defaultLabel: "Checkpoint",
      noDiff: "暂无 Diff。",
      diffLoadError: (msg: string) => `加载 Diff 失败：${msg}`,
      labelPlaceholder: "Checkpoint 名称",
      messagePlaceholder: "可选留言",
      create: "创建",
      loading: "正在加载 Checkpoint…",
      loadingDiff: "正在加载 Diff…",
      fileCount: (n: number) => `${n} 个文件`,
      emptyHint: "点击「创建」保存当前工作区快照。",
    },
    codebase: {
      title: "代码库",
      refresh: "刷新",
      status: "状态",
      progress: "进度",
      files: (n: number) => `文件：${n}`,
      chunks: (n: number) => `分块：${n}`,
      buildIndex: "构建索引",
      loadingStatus: "正在加载状态…",
      searchPlaceholder: "搜索代码（如 auth flow）",
      searchAria: "搜索",
      searching: "正在搜索…",
      searchEmptyHint: "输入关键词并点击搜索，或先构建索引。",
      matchCount: (n: number) => `${n} 次匹配`,
      summaryPathPlaceholder: "总结路径（如 src/auth.ts）",
      summary: "总结",
      lineCount: (n: number) => `${n} 行`,
      fileCount: (n: number) => `${n} 个文件`,
    },
    terminal: {
      cwdPlaceholder: "cwd（默认为工作区根目录）",
      runCommand: "运行命令",
      refresh: "刷新终端",
      stop: "停止命令",
      error: "终端错误",
      newOutput: "新输出",
    },
    runner: {
      title: "Runners",
      refreshAria: "刷新 Runners",
      askPlaceholder: "向此 Runner 提问",
      startAria: "启动 Runner",
      sandbox: "沙箱",
      approval: "审批",
      permission: "权限",
      adapterPending: "适配器待接入",
      loading: "加载中…",
    },
    subagents: {
      idle: "空闲",
      runCount: (n: number) => `${n} 个运行`,
      clearDone: "清除已完成",
      clearDoneTitle: "从列表中清除已完成/失败的运行",
      cancelTitle: "取消此运行",
      progressAria: "进度",
      failedTitle: "子 Agent 失败",
      status: {
        started: "已启动",
        thinking: "思考中",
        tool_call: "工具调用",
        tool_result: "工具结果",
        completed: "已完成",
        failed: "已失败",
        cancelled: "已取消",
      },
    },
    progress: {
      title: "进度",
      runningCount: (n: number) => `${n} 个运行中`,
      refreshTitle: "刷新任务台账",
      cancelTitle: "取消任务",
      dismissTitle: "移除任务",
      agentCrashed: "agent 已崩溃",
      mockBackend: "mock 后端",
    },
    agents: {
      teamTitle: "Agent 团队",
      refreshAria: "刷新 Agent 列表",
      loading: "正在加载 Agent…",
      loadFailed: "加载 Agent 失败",
      idle: "空闲",
      disabled: "已禁用",
      running: "运行中",
      done: "已完成",
    },
    teamRuns: {
      title: "团队运行",
      activeCount: (n: number) => `${n} 个进行中`,
      agentCount: (completed: number, total: number) => `${completed}/${total} 个 Agent`,
      running: (name: string) => `正在运行：${name}`,
      conflicts: (n: number) => `检测到 ${n} 个文件冲突`,
      removeAria: "移除团队运行",
    },
    resultCard: {
      unavailable: "子 Agent 结果不可用",
      failed: "失败",
      completed: "已完成",
      openTitle: "在子 Agent 面板中打开",
      openRun: "打开运行",
      collapse: "收起",
      expand: "展开",
      failedTitle: "子 Agent 失败",
    },
  },
  a11y: {
    navigation: "导航",
    closeOverlay: "关闭浮层",
    closeDialog: "关闭对话框",
    loading: "加载中",
  },
} as const;

export type Strings = typeof strings;
