"""Notification storage.

Stores user-visible notifications generated by the agent, webhooks,
workflows, and other subsystems.  Each notification has a type,
priority, and read/unread state.

v0.7.0 — Mobile Connectivity Enhancement.
"""

from __future__ import annotations

from typing import Any

from . import run_script

VERSION = 8

DDL = r"""
-- ---------------------------------------------------------------------------
-- notifications (user-facing notification center)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id          TEXT PRIMARY KEY,           -- 'ntf_' + uuid hex[:10]
    type        TEXT NOT NULL,              -- 'info'|'warning'|'error'|'webhook'|'permission'|'workflow'
    title       TEXT NOT NULL,
    body        TEXT NOT NULL DEFAULT '',
    source      TEXT,                       -- 'system'|'webhook'|'workflow'|'schedule'|'agent'
    source_id   TEXT,                       -- FK hint (webhook_id, workflow_id, etc.)
    priority    INTEGER NOT NULL DEFAULT 0, -- 0=normal, 1=high, 2=urgent
    read        INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    read_at     TEXT
);
CREATE INDEX IF NOT EXISTS idx_notifications_read    ON notifications(read);
CREATE INDEX IF NOT EXISTS idx_notifications_type    ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC);
"""


def run(conn: Any) -> None:
    """Apply the notifications migration to ``conn``."""
    run_script(conn, DDL)


__all__ = ["DDL", "VERSION", "run"]
