"""Shared API definitions for Grok tools (R190-R192, complete -- crate milestone).

Fusion of grok-build's ``xai-grok-tools-api`` crate (613 lines / 3 files):
protobuf types, config validation, and canonical slash-command wording. Used by
both the tools library and the gRPC server, and by host services that must not
depend on the tools implementation crate.

``pub mod pb`` YAGNI (platform adaptation)
------------------------------------------

The crate's bulk is ``pub mod pb``: ~60 protobuf wire types
(``AgentCompletionRequirement``, ``ExecuteToolRequest``, ``ErrorCode``,
``ToolCategory``, ...) generated by tonic/build.rs from ``.proto`` schemata, plus
the root-level ``pub use pb::{...}`` re-export and the ``impl ToolCategory {
as_str }`` block. The platform has **no protobuf compilation pipeline** (no
``.proto`` + ``protoc`` + build.rs) and **no gRPC tools server consumer** (the
platform speaks JSON-RPC over HTTP/WS + httpx for the LLM, not gRPC tool RPCs),
so ``pb`` is intentionally not migrated -- including ``ToolCategory`` and its
``as_str`` method, which is an inherent impl on the pb-generated enum and so
travels with the type. Mirrors the R132 ``grpc_client`` / OTel SDK YAGNI
pattern: documented divergence, not an oversight. If a future gRPC tools
surface lands, regenerate ``pb`` from the canonical ``.proto`` rather than
hand-porting; ``ToolCategory::as_str`` comes back for free with the type.

Leaf order
----------

1. ``slash_commands`` (R190) -- canonical ``/loop`` / ``/imagine`` /
   ``/imagine-video`` / ``/goal`` wording. Zero dependencies (pure strings +
   format), the crate's most self-contained leaf; landed first to establish the
   package skeleton.
2. ``config_validation`` (R191) -- ``ToolConfigEntryError`` +
   ``parse_params_json`` + ``validate_name_override`` + ``first_unknown_tool_id``;
   consumes R82 ``tool_protocol.ToolId``.
3. ``lib.rs`` barrel-reconciliation (R192, landed) -- ``default_client_name`` at
   the barrel root (the crate's only non-pb free function) + final pb YAGNI
   ledger. Crate complete.

Barrel surface
--------------

Rust re-exports the 60 ``pb`` symbols at the crate root (YAGNI here). The
``slash_commands`` / ``config_validation`` modules are plain ``pub mod``
(accessed as ``crate::slash_commands::foo()``), so the platform barrel mirrors
that: it exposes the submodules, not their inner symbols.
``default_client_name`` is a free function in ``lib.rs`` (not a re-export), so
it lands at the barrel root as ``tools_api.default_client_name``.
"""

from __future__ import annotations

from minimax_code.tools_api import config_validation, slash_commands

__all__ = ["config_validation", "default_client_name", "slash_commands"]


def default_client_name(id: str) -> str:
    """Default client-facing tool name derived from a namespaced tool id.

    Tool ids are colon-separated ``Namespace:tool`` (e.g. ``GrokBuild:grep``);
    the default name is the segment after the FIRST colon, so an id with
    embedded colons (``ns:a:b``) resolves to ``a``. Ids without a colon are
    returned as-is.

    Single source of truth shared by the tools server (which advertises tools
    under this name unless ``name_override`` is set) and any client that needs
    to predict the advertised name from a config entry (e.g. prompt tool
    selection in a downstream service). Keeping both sides on this helper
    prevents a silent desync that would drop tools from prompts.

    Mirrors ``lib.rs::default_client_name``: ``id.split(':').nth(1).unwrap_or(id)``
    -- Python splits on every colon and takes the second segment, falling back
    to the whole id when there is none.
    """
    segments = id.split(":")
    return segments[1] if len(segments) >= 2 else id


#: pb YAGNI ledger (R190 architecture decision; R192 crate-complete)
#: -------------------------------------------------------------------
#: grok-build ``xai-grok-tools-api/src/lib.rs`` declares ``pub mod pb``
#: (~60 protobuf wire types via tonic/build.rs codegen) + root ``pub use pb::{...}``
#: + ``impl ToolCategory { as_str }``. NOT migrated:
#:   - no protobuf compilation pipeline on the platform (no .proto + protoc);
#:   - no gRPC tools server consumer (platform uses JSON-RPC + httpx).
#: ``ToolCategory`` and its ``as_str`` method travel with the pb type (inherent
#: impl on a codegen enum); both return when pb is regenerated. Mirrors R132
#: grpc_client / OTel SDK YAGNI. Crate COMPLETE (R190-R192):
#:   slash_commands R190 (landed), config_validation R191 (landed),
#:   lib.rs barrel-reconciliation R192 (landed, default_client_name at root).
