"""Shared API definitions for Grok tools (R190-R192, in progress).

Fusion of grok-build's ``xai-grok-tools-api`` crate (613 lines / 3 files):
protobuf types, config validation, and canonical slash-command wording. Used by
both the tools library and the gRPC server, and by host services that must not
depend on the tools implementation crate.

``pub mod pb`` YAGNI (platform adaptation)
------------------------------------------

The crate's bulk is ``pub mod pb``: ~60 protobuf wire types
(``AgentCompletionRequirement``, ``ExecuteToolRequest``, ``ErrorCode``,
``ToolCategory``, ...) generated by tonic/build.rs from ``.proto`` schemata. The
platform has **no protobuf compilation pipeline** (no ``.proto`` + ``protoc`` +
build.rs) and **no gRPC tools server consumer** (the platform speaks JSON-RPC
over HTTP/WS + httpx for the LLM, not gRPC tool RPCs), so the ``pb`` module is
intentionally not migrated. Mirrors the R132 ``grpc_client`` / OTel SDK YAGNI
pattern: documented divergence, not an oversight. If a future gRPC tools
surface lands, regenerate ``pb`` from the canonical ``.proto`` rather than
hand-porting.

Leaf order
----------

1. ``slash_commands`` (R190) -- canonical ``/loop`` / ``/imagine`` /
   ``/imagine-video`` / ``/goal`` wording. Zero dependencies (pure strings +
   format), the crate's most self-contained leaf; landed first to establish the
   package skeleton.
2. ``config_validation`` (R191, planned) -- ``ToolConfigEntryError`` +
   ``parse_params_json`` + ``validate_name_override`` + ``first_unknown_tool_id``;
   consumes R82 ``tool_protocol.ToolId``.
3. ``lib.rs`` barrel-reconciliation (R192, planned) -- ``default_client_name``
   + ``ToolCategory`` decision (pb-attached, follows ``pb`` YAGNI) + final ledger.

Barrel surface
--------------

Rust re-exports the 60 ``pb`` symbols at the crate root (YAGNI here). The
``slash_commands`` / ``config_validation`` modules are plain ``pub mod``
(accessed as ``crate::slash_commands::foo()``), so the platform barrel mirrors
that: it exposes the submodules, not their inner symbols.
``default_client_name`` lands at the barrel root in R192 (it is a free function
in ``lib.rs``, not a re-export).
"""

from __future__ import annotations

from minimax_code.tools_api import config_validation, slash_commands

__all__ = ["config_validation", "slash_commands"]

#: pb YAGNI ledger (R190 architecture decision)
#: ---------------------------------------------
#: grok-build ``xai-grok-tools-api/src/lib.rs`` declares ``pub mod pb``
#: (~60 protobuf wire types via tonic/build.rs codegen). NOT migrated:
#:   - no protobuf compilation pipeline on the platform (no .proto + protoc);
#:   - no gRPC tools server consumer (platform uses JSON-RPC + httpx).
#: Mirrors R132 grpc_client / OTel SDK YAGNI. Crate IN PROGRESS (R190-R192):
#:   slash_commands R190 (landed), config_validation R191 (planned),
#:   lib.rs barrel-reconciliation R192 (planned, crate milestone).
